### ISSUE TITLE
Vote shows only for one player

### ISSUE THREAD

**Issue by mo0nsniper** [evandrocoan/MultiModServer#26] opened 2016-11-09 13:44 UTC
Hello,

I'm having a problem where the vote only shows up only for one player. So only one player sees the vote all the time and the rest don't.

I have sent you the details by email.

Cheers

**Comment by evandrocoan** [comment] 2016-11-09 23:08
Hi, 

I got your email and data, but I do not have the time to review this right now. Only next week.

But this is a really big problem, if I am understanding correctly.
With this bug, there is no voting, makes this plugin purely useless.

I would recommend switch to the another map chooser or for the first version 1.1.290, which surely work, until this got fixed. To move to the older version, just replacing the `galileo.amxx` should be enough.

**Comment by evandrocoan** [comment] 2016-11-11 21:22
> I got your email and data, but I do not have the time to review this right now. Only next week.

I engaged on another project, so I do not have time for fix next week. Only after 10 of December.

**Comment by evandrocoan** [comment] 2016-11-12 12:15
Hi, you settings is very sensitive to not showing the menu because `gal_vote_showstatus` and `gal_vote_replace_menu` are 0. This way if the player has some menu open, as the weapon buy menu, he will not see the voting menu, because the cvar `gal_vote_replace_menu` will not replace it and the cvar `gal_vote_showstatus` is not set as 3.

```
// Indicates when the vote progress should be shown to a player.
// A value of 0 disables this feature.
// 0 - never (this disables the cvar 'gal_vote_expirationcountdown')
// 1 - after player has voted
// 2 - after the vote ends (this disables the cvar 'gal_vote_expirationcountdown')
// 3 - always show the vote current progress
gal_vote_showstatus 0

// Indicates whether to replace any menu opened by the server players,
// when a voting is started, or to wait that menu to be closed before
// showing the voting menu.
// 0 - Waits the user to close his current menu, only then show the
//     new menu.
// 1 - Replace any opened menu.
gal_vote_replace_menu 0
```

One way to fix this would be enable the cvar `gal_endofmapvote_start`, this way the voting would try to start after the weapons menu being showed on the round start.

``` pawn
// Indicates whether there should be created a 4 minutes range before 
// approximately the last 2 minutes and 22 seconds to detect a round start
// and to give time about 20 seconds to buy weapons after the round to start
// and before the map voting to start.
// 0 - disabled this feature
// 1 - enable this feature
gal_endofmapvote_start 1
```

**Comment by evandrocoan** [comment] 2016-11-12 12:17
The enhancement here is to the cvar `gal_vote_showstatus` set as 0, 1 and 2, when the cvar `gal_vote_replace_menu` is set to 0. Detect which players are not able to see the voting menu and show it to them as soon as possible.

**Comment by evandrocoan** [comment] 2016-11-12 18:31
@mo0nsniper, I am not actually convinced that this fixed the issue. But it does not mean I cannot fix it.
It will just cost a little more work from you. On the lasted version v3.2.5 released on the forum, I added some more debug messages to help determinate why the issue is coming. But I do not added everything possible, so if the issue persists, two more steps are being necessary:
1. Could you try to see if the issue continue even with the `gal_vote_showstatus` set to 3?
2. Send me again a new `_galileo.log` file running the version 3.2.5 on debug mode.

After the step 2, I would get more closer to why the voting is not showing up.

**Comment by evandrocoan** [comment] 2016-11-13 20:23
The enhancement:

> The enhancement here is to the cvar gal_vote_showstatus set as 0, 1 and 2, when the cvar gal_vote_replace_menu is set to 0. Detect which players are not able to see the voting menu and show it to them as soon as possible.

Is already implemented and the initial reported bug is finally fixed. Finally closing this issue.

**Closed as completed by evandrocoan** 2016-11-13 20:23 UTC
Labels: Type: enhancement, Severity: minor

**Comment by mo0nsniper** [comment] 2016-11-14 11:17
@evandrocoan I didn't have time to test it over the week-end but I see you still fixed the issue.
Thank you very much. I will install the new version.
